application: datastore-endpoints
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: picturestore.application

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
